# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Album')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Video')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='videos',
            field=models.ManyToManyField(through='cms.VideoAlbum', to='cms.Video'),
        ),
    ]
