# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoalbum',
            unique_together=set([('video', 'album')]),
        ),
    ]
