# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180403_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoalbum',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='videoalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='videoalbum',
            name='video',
        ),
        migrations.AlterField(
            model_name='album',
            name='videos',
            field=models.ManyToManyField(to='cms.Video'),
        ),
        migrations.DeleteModel(
            name='VideoAlbum',
        ),
    ]
