# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180412_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='videos',
            field=models.ManyToManyField(through='cms.VideoAlbum', to='cms.Video'),
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Album'),
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='videoalbum',
            unique_together=set([('video', 'album')]),
        ),
    ]
