# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms_test.Category')),
            ],
        ),
    ]
