# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test', '0002_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='categories',
            field=models.ManyToManyField(to='cms_test.Category'),
        ),
    ]
