# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test', '0003_episode_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_test.Category')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_test.Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(through='cms_test.VideoCategory', to='cms_test.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='videocategory',
            unique_together=set([('video', 'category')]),
        ),
    ]
