# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test', '0005_auto_20180411_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='videocategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='videocategory',
            old_name='video_id',
            new_name='video',
        ),
        migrations.AlterUniqueTogether(
            name='videocategory',
            unique_together=set([('video', 'category')]),
        ),
    ]
