# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test', '0006_auto_20180411_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test.Language'),
        ),
    ]
