# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test', '0007_auto_20180411_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test.Category')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms_test.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_test.Genre')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_test.Video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(through='cms_test.VideoGenre', to='cms_test.Genre'),
        ),
        migrations.AlterUniqueTogether(
            name='videogenre',
            unique_together=set([('video', 'genre')]),
        ),
    ]
