# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test', '0010_auto_20180411_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortVideoInfo',
            fields=[
                ('short_video_info_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
