# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
