# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0005_auto_20180412_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodelangpack',
            name='actors',
            field=models.ManyToManyField(related_name='_episodelangpack_actors_+', to='cms_test2.Actor'),
        ),
        migrations.AddField(
            model_name='episodelangpack',
            name='directors',
            field=models.ManyToManyField(related_name='_episodelangpack_directors_+', to='cms_test2.Director'),
        ),
        migrations.AlterField(
            model_name='episodelangpack',
            name='thumbnails',
            field=models.ManyToManyField(related_name='_episodelangpack_thumbnails_+', to='cms_test2.Thumbnail'),
        ),
        migrations.AlterField(
            model_name='shortvideolangpack',
            name='thumbnails',
            field=models.ManyToManyField(related_name='_shortvideolangpack_thumbnails_+', to='cms_test2.Thumbnail'),
        ),
    ]
