# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0008_video_movie_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInfo',
            fields=[
                ('music_info_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MusicLangPack',
            fields=[
                ('music_langpack_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_default', models.PositiveIntegerField(blank=True, choices=[(0, 'not default language'), (1, 'is default language')], null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('composers', models.ManyToManyField(related_name='_musiclangpack_composers_+', to='cms_test2.Composer')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.Language')),
                ('lyricists', models.ManyToManyField(related_name='_musiclangpack_lyricists_+', to='cms_test2.Lyricist')),
                ('music_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.MusicInfo')),
                ('recordlabels', models.ManyToManyField(related_name='_musiclangpack_recordlabels_+', to='cms_test2.RecordLabel')),
                ('thumbnails', models.ManyToManyField(related_name='_musiclangpack_thumbnails_+', to='cms_test2.Thumbnail')),
            ],
        ),
    ]
