# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0010_auto_20180412_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_end',
            field=models.PositiveIntegerField(choices=[(0, 'not end'), (1, 'end')], default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0),
        ),
    ]
