# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0011_auto_20180412_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonInfo',
            fields=[
                ('season_info_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonLangPack',
            fields=[
                ('season_langpack_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_default', models.PositiveIntegerField(choices=[(0, 'not default language'), (1, 'is default language')], default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon', models.CharField(blank=True, max_length=300, null=True)),
                ('album_pic', models.CharField(blank=True, max_length=300, null=True)),
                ('actors', models.ManyToManyField(to='cms_test2.Actor')),
                ('directors', models.ManyToManyField(to='cms_test2.Director')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.Language')),
                ('season_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.SeasonInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='cms_test2.Genre'),
        ),
        migrations.AlterField(
            model_name='episodelangpack',
            name='actors',
            field=models.ManyToManyField(to='cms_test2.Actor'),
        ),
        migrations.AlterField(
            model_name='episodelangpack',
            name='directors',
            field=models.ManyToManyField(to='cms_test2.Director'),
        ),
        migrations.AlterField(
            model_name='episodelangpack',
            name='is_default',
            field=models.PositiveIntegerField(choices=[(0, 'not default language'), (1, 'is default language')], default=0),
        ),
        migrations.AlterField(
            model_name='episodelangpack',
            name='thumbnails',
            field=models.ManyToManyField(to='cms_test2.Thumbnail'),
        ),
        migrations.AlterField(
            model_name='movielangpack',
            name='actors',
            field=models.ManyToManyField(to='cms_test2.Actor'),
        ),
        migrations.AlterField(
            model_name='movielangpack',
            name='directors',
            field=models.ManyToManyField(to='cms_test2.Director'),
        ),
        migrations.AlterField(
            model_name='movielangpack',
            name='is_default',
            field=models.PositiveIntegerField(choices=[(0, 'not default language'), (1, 'is default language')], default=0),
        ),
        migrations.AlterField(
            model_name='movielangpack',
            name='thumbnails',
            field=models.ManyToManyField(to='cms_test2.Thumbnail'),
        ),
        migrations.AlterField(
            model_name='musiclangpack',
            name='composers',
            field=models.ManyToManyField(to='cms_test2.Composer'),
        ),
        migrations.AlterField(
            model_name='musiclangpack',
            name='is_default',
            field=models.PositiveIntegerField(choices=[(0, 'not default language'), (1, 'is default language')], default=0),
        ),
        migrations.AlterField(
            model_name='musiclangpack',
            name='lyricists',
            field=models.ManyToManyField(to='cms_test2.Lyricist'),
        ),
        migrations.AlterField(
            model_name='musiclangpack',
            name='recordlabels',
            field=models.ManyToManyField(to='cms_test2.RecordLabel'),
        ),
        migrations.AlterField(
            model_name='musiclangpack',
            name='thumbnails',
            field=models.ManyToManyField(to='cms_test2.Thumbnail'),
        ),
        migrations.AlterField(
            model_name='shortvideolangpack',
            name='is_default',
            field=models.PositiveIntegerField(choices=[(0, 'not default language'), (1, 'is default language')], default=0),
        ),
        migrations.AlterField(
            model_name='shortvideolangpack',
            name='thumbnails',
            field=models.ManyToManyField(to='cms_test2.Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(to='cms_test2.Category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(to='cms_test2.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='season_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.SeasonInfo'),
        ),
    ]
