# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0012_auto_20180412_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbumInfo',
            fields=[
                ('musicalbum_info_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MusicAlbumLangPack',
            fields=[
                ('musicalbum_langpack_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_default', models.PositiveIntegerField(choices=[(0, 'not default language'), (1, 'is default language')], default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.Language')),
                ('musicalbum_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.MusicAlbumInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SequelInfo',
            fields=[
                ('sequel_info_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SequelLangPack',
            fields=[
                ('sequel_langpack_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_default', models.PositiveIntegerField(choices=[(0, 'not default language'), (1, 'is default language')], default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.Language')),
                ('sequel_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.SequelInfo')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='musicalbum_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.MusicAlbumInfo'),
        ),
        migrations.AddField(
            model_name='album',
            name='sequel_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.SequelInfo'),
        ),
    ]
