# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0015_auto_20180413_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='artist_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_test2.ArtistInfo'),
        ),
    ]
