# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0017_auto_20180413_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('banner_name', models.CharField(max_length=100)),
                ('poster', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('platform_id', models.PositiveIntegerField(blank=True, choices=[(1, 'Android'), (2, 'IOS'), (3, 'Web')], default=1, null=True)),
                ('position_id', models.PositiveIntegerField(blank=True, choices=[(1, 'home'), (2, 'buzz'), (3, 'music'), (4, 'browser')], default=1, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
