# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0021_auto_20180413_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'publisher'), (2, 'tv show'), (21, 'channel-->tv show'), (22, 'album-->season'), (23, 'video-->episode'), (3, 'music'), (31, 'channel-->artist'), (32, 'album-->album'), (33, 'music-->music video'), (34, 'playlist'), (4, 'movie'), (41, 'album-->sequel'), (42, 'video-->movie video'), (5, 'short video')], null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='platform_id',
            field=models.PositiveIntegerField(choices=[(1, 'Android'), (2, 'IOS'), (3, 'Web')], default=1),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position_id',
            field=models.PositiveIntegerField(choices=[(1, 'home'), (2, 'buzz'), (3, 'music'), (4, 'browser')], default=1),
        ),
    ]
