# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cms_test2', '0022_auto_20180413_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_fk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
