# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0023_auto_20180413_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardList',
            fields=[
                ('card_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=100)),
            ],
        ),
    ]
