# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test2', '0024_cardlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardlistCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('status', models.PositiveIntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0)),
                ('list_style', models.CharField(blank=True, choices=[('1', 'list style 1'), ('2', 'list style 2')], max_length=100, null=True)),
                ('more_style', models.CharField(blank=True, choices=[('1', 'more style 1'), ('2', 'more style 2')], max_length=100, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_test2.Card')),
            ],
        ),
        migrations.RenameField(
            model_name='cardlist',
            old_name='card_id',
            new_name='cardlist_id',
        ),
        migrations.RenameField(
            model_name='cardlist',
            old_name='card_name',
            new_name='cardlist_name',
        ),
        migrations.AddField(
            model_name='cardlist',
            name='platform_id',
            field=models.PositiveIntegerField(choices=[(1, 'Android'), (2, 'IOS'), (3, 'Web')], default=1),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='position_id',
            field=models.PositiveIntegerField(choices=[(1, 'home'), (2, 'buzz'), (3, 'music'), (4, 'browser')], default=1),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='tab_style',
            field=models.CharField(blank=True, choices=[('1', 'tab style 1'), ('2', 'tab style 2')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardlistcard',
            name='cardlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_test2.CardList'),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='cards',
            field=models.ManyToManyField(through='cms_test2.CardlistCard', to='cms_test2.Card'),
        ),
        migrations.AlterUniqueTogether(
            name='cardlistcard',
            unique_together=set([('cardlist', 'card')]),
        ),
    ]
