# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cms_test2', '0025_auto_20180413_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('carditem_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('unit_type', models.PositiveIntegerField(choices=[(1, 'publisher publisher'), (2, 'tvshow category'), (21, 'tvshow channnel'), (22, 'season album'), (23, 'episode video')], default=1)),
                ('content_type', models.PositiveIntegerField(choices=[(1, 'publisher publisher'), (2, 'tvshow category'), (21, 'tvshow channnel'), (22, 'season album'), (23, 'episode video')], default=1)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_test2.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardItemContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_fk', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField()),
                ('carditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_test2.CardItem')),
                ('content_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='carditem',
            name='contents',
            field=gm2m.fields.GM2MField(through=b'cms_test2.CardItemContent', through_fields=[b'carditem', b'content', 'content_ct', 'content_fk']),
        ),
    ]
